[build]
  command = "npm install --no-save @rolldown/binding-linux-x64-gnu@1.0.0-rc.12 && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.12.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
